backend:
  name: github
  repo: ondraondra81/votava.blog

media_folder: static/images
public_folder: images
publish_mode: editorial_workflow

collections:
- name: blog
  label: Blog
  folder: src/pages
  create: true
  fields:
  - { name: 'path', label: 'Path' }
  - { name: 'draft', label: 'Draft', widget: 'boolean', default: true }
  - { name: 'date', label: 'Date', widget: 'date' }
  - { name: 'title', label: 'Title' }
  - { name: "featuredImage", label: "Featured Image", widget: "image", required: false}
  - { name: 'body', label: 'Body', widget: 'markdown' }
