backend:
  name: github
  repo: ondraondra81/votava.blog

media_folder: src/pages/assets

collections:
- name: blog
  label: Blog
  folder: src/pages
  create: true
  fields:
  - { name: 'path', label: 'Path' }
  - { name: 'draft', label: 'Draft', widget: 'boolean' }
  - { name: 'date', label: 'Date', widget: 'date' }
  - { name: 'title', label: 'Title' }
  - { name: "featuredImage", label: "Featured Image", widget: "image"}
  - { name: 'body', label: 'Body', widget: 'markdown' }
