backend:
  name: github
  repo: ondraondra81/votava.blog

media_folder: /static/images
public_folder: /images
publish_mode: editorial_workflow

slug:
  encoding: unicode
  clean_accents: true

collections:
- name: blog
  label: Blog
  folder: src/pages
  create: true
  fields:
  - { name: 'date', label: 'Date', widget: 'date' }
  - { name: 'title', label: 'Title' }
  - { name: "featuredImage", label: "Featured Image", widget: "image", required: false}
  - { name: 'body', label: 'Body', widget: 'markdown' }
