backend:
  name: github
  repo: ondraondra81/votava.blog

media_folder: src/pages/assets

collections:
- name: blog
  label: Blog
  folder: src/pages
  create: true
  fields:
#  - { name: path, label: Path }
  - { name: date, label: Date, widget: date }
  - { name: title, label: Title }
  - { name: body, label: Body, widget: markdown }
